# Generated by Django 2.0.1 on 2018-01-18 15:15

import biography.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_auto_20180117_2043'),
        ('biography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('private', 'Private'), ('government', 'Public - Government'), ('military', 'Public - Military'), ('public', 'Public - Other')], default='private', max_length=10)),
                ('title', models.CharField(max_length=250)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('notes', biography.fields.MarkdownField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='biography',
            options={'verbose_name_plural': 'biographies'},
        ),
        migrations.AlterModelOptions(
            name='birthplace',
            options={'verbose_name_plural': 'birthplace'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'education'},
        ),
        migrations.AlterModelOptions(
            name='ideology',
            options={'verbose_name_plural': 'ideology'},
        ),
        migrations.AlterModelOptions(
            name='legislation',
            options={'verbose_name_plural': 'Legislative accomplishments'},
        ),
        migrations.AddField(
            model_name='quotetopic',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occupation',
            name='biography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='biography.Biography'),
        ),
        migrations.AddField(
            model_name='occupation',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Optionally, associate this occupation with an organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='entity.Organization'),
        ),
    ]
