# Generated by Django 2.1.3 on 2018-11-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0002_auto_20180118_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideologycategory',
            options={'verbose_name_plural': 'ideology categories'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name_plural': 'Published works'},
        ),
        migrations.AddField(
            model_name='occupation',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biography',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(),
        ),
    ]
