# Generated by Django 2.1.3 on 2018-11-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0003_auto_20181127_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
