# Generated by Django 2.1.3 on 2018-11-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0004_education_graduation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree_program',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
