# Generated by Django 2.1.3 on 2018-12-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0006_residence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='QuoteTopic',
        ),
    ]
