# Generated by Django 2.1.3 on 2018-12-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0007_auto_20181207_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
