# Generated by Django 2.1.3 on 2019-01-03 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0003_office_senate_class'),
        ('biography', '0009_auto_20181221_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('notes', models.TextField(blank=True, null=True)),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='biography.Biography')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government.Office')),
            ],
        ),
    ]
